services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  backend:
    # build: ./backend
    image: shivam7000/dockerproject-backend
    container_name: backend
    ports:
      - 5000:5000
    environment:
      DB_URI: mongodb://admin:password@mongodb:27017/bug-tracker?authSource=admin
    depends_on:
      - mongodb
      
  frontend:
    # build: ./frontend
    image: shivam7000/dockerproject-frontend
    container_name: frontend
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo-data:
